name = "word-blast-api"
main = "worker/index.js"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "word-blast-db"
database_id = "054a337d-cec2-435c-9741-4b08c5e7e327"
